### ISSUE TITLE
밑줄이 있는 label

### ISSUE THREAD

**Issue by KwonDoby** [inkyfox/KRWordWrapLabel#2]
안녕하세요. 한국분인거 같아서 한국어로 글남깁니다.
제가 지금 밑줄이 있는 label을 사용하려 하는데 작동이 되지않습니다.

cell.labelThemeTitle?.attributedText = NSAttributedString(string: self.categotyThemes[indexPath.row].title!, attributes: [NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue])

코드 첨부드립니다.

좋은 라이브러리에 감사드립니다 :)

**Comment by inkyfox** [comment]
Swift4에서는
`[NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue]`
부분을
`[NSAttributedStringKey.underlineStyle: NSUnderlineStyle.styleSingle]`
로 수정하시면 될 것 같습니다.
